# Get VPC and Subnets for this Account

    - name: Get VPC ID
      ec2_vpc_net_info:
        aws_access_key: "{{ your_aws_cred.AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ your_aws_cred.AWS_SECRET_ACCESS_KEY }}"
        region: "{{ region }}"
      register: VPC
    - set_fact:
        VPC_ID: "{{ VPC.vpcs[0].vpc_id }}"

    - name: Get Subnet A for VPC
      ec2_vpc_subnet_info:
        aws_access_key: "{{ your_aws_cred.AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ your_aws_cred.AWS_SECRET_ACCESS_KEY }}"
        region: "{{ region }}"
        filters:
          vpc-id: "{{ VPC_ID }}"
          "tag:Name": "Application Tier AZ-a"
      register: SubnetA
    - set_fact:
        SubnetA_ID: "{{ SubnetA.subnets[0].subnet_id }}"

    - name: Get Subnet B for VPC
      ec2_vpc_subnet_info:
        aws_access_key: "{{ your_aws_cred.AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ your_aws_cred.AWS_SECRET_ACCESS_KEY }}"
        region: "{{ region }}"
        filters:
          vpc-id: "{{ VPC_ID }}"
          "tag:Name": "Application Tier AZ-b"
      register: SubnetB
    - set_fact:
        SubnetB_ID: "{{ SubnetB.subnets[0].subnet_id }}"
